package net.glasslauncher.mixin.modloader;

import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.glasslauncher.modloader.ModLoader;
import net.minecraft.block.BlockBase;
import net.minecraft.client.render.TileRenderer;
import net.minecraft.level.TileView;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Shadow;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.Redirect;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

@Mixin(TileRenderer.class)
public abstract class MixinRenderBlocks {

    @Shadow private TileView field_82;
    @Shadow private int field_83;
    @Shadow private boolean field_84;
    @Shadow private boolean field_85;
    @Shadow public boolean field_81;
    @Shadow private int field_86;
    @Shadow private int field_87;
    @Shadow private int field_88;
    @Shadow private int field_89;
    @Shadow private int field_90;
    @Shadow private int field_91;
    @Shadow private boolean field_92;
    @Shadow private float field_93;
    @Shadow private float field_94;
    @Shadow private float field_95;
    @Shadow private float field_96;
    @Shadow private float field_97;
    @Shadow private float field_98;
    @Shadow private float field_99;
    @Shadow private float field_100;
    @Shadow private float field_101;
    @Shadow private float field_102;
    @Shadow private float field_103;
    @Shadow private float field_104;
    @Shadow private float field_105;
    @Shadow private float field_41;
    @Shadow private float field_42;
    @Shadow private float field_43;
    @Shadow private float field_44;
    @Shadow private float field_45;
    @Shadow private float field_46;
    @Shadow private float field_47;
    @Shadow private float field_48;
    @Shadow private float field_49;
    @Shadow private float field_50;
    @Shadow private float field_51;
    @Shadow private float field_52;
    @Shadow private float field_53;
    @Shadow private float field_54;
    @Shadow private int field_55;
    @Shadow private float field_56;
    @Shadow private float field_57;
    @Shadow private float field_58;
    @Shadow private float field_59;
    @Shadow private float field_60;
    @Shadow private float field_61;
    @Shadow private float field_62;
    @Shadow private float field_63;
    @Shadow private float field_64;
    @Shadow private float field_65;
    @Shadow private float field_66;
    @Shadow private float field_68;
    @Shadow private boolean field_69;
    @Shadow private boolean field_70;
    @Shadow private boolean field_71;
    @Shadow private boolean field_72;
    @Shadow private boolean field_73;
    @Shadow private boolean field_74;
    @Shadow private boolean field_75;
    @Shadow private boolean field_76;
    @Shadow private boolean field_77;
    @Shadow private boolean field_78;
    @Shadow private boolean field_79;
    @Shadow private boolean field_80;

    @Inject(method = "<init>(Lnet/minecraft/level/TileView;)V", at = @At(value = "RETURN"))
    public void initIBlockAccess(TileView iBlockAccess, CallbackInfo callbackInfo) {
        this.field_82 = iBlockAccess;
        this.field_82 = null;
        this.field_83 = 0;
        this.field_84 = false;
        this.field_85 = false;
        this.field_81 = false;
        this.field_86 = 0;
        this.field_87 = 0;
        this.field_88 = 0;
        this.field_89 = 0;
        this.field_90 = 0;
        this.field_91 = 0;
        this.field_92 = false;
        this.field_93 = 0.0f;
        this.field_94 = 0.0f;
        this.field_95 = 0.0f;
        this.field_96 = 0.0f;
        this.field_97 = 0.0f;
        this.field_98 = 0.0f;
        this.field_99 = 0.0f;
        this.field_100 = 0.0f;
        this.field_101 = 0.0f;
        this.field_102 = 0.0f;
        this.field_103 = 0.0f;
        this.field_104 = 0.0f;
        this.field_105 = 0.0f;
        this.field_41 = 0.0f;
        this.field_42 = 0.0f;
        this.field_43 = 0.0f;
        this.field_44 = 0.0f;
        this.field_45 = 0.0f;
        this.field_46 = 0.0f;
        this.field_47 = 0.0f;
        this.field_48 = 0.0f;
        this.field_49 = 0.0f;
        this.field_50 = 0.0f;
        this.field_51 = 0.0f;
        this.field_52 = 0.0f;
        this.field_53 = 0.0f;
        this.field_54 = 0.0f;
        this.field_55 = 0;
        this.field_56 = 0.0f;
        this.field_57 = 0.0f;
        this.field_58 = 0.0f;
        this.field_59 = 0.0f;
        this.field_60 = 0.0f;
        this.field_61 = 0.0f;
        this.field_62 = 0.0f;
        this.field_63 = 0.0f;
        this.field_64 = 0.0f;
        this.field_65 = 0.0f;
        this.field_66 = 0.0f;
        this.field_68 = 0.0f;
        this.field_69 = false;
        this.field_70 = false;
        this.field_71 = false;
        this.field_72 = false;
        this.field_73 = false;
        this.field_74 = false;
        this.field_75 = false;
        this.field_76 = false;
        this.field_77 = false;
        this.field_78 = false;
        this.field_79 = false;
        this.field_80 = false;
        this.field_83 = -1;
        this.field_84 = false;
        this.field_85 = false;
        this.field_81 = true;
        this.field_86 = 0;
        this.field_87 = 0;
        this.field_88 = 0;
        this.field_89 = 0;
        this.field_90 = 0;
        this.field_91 = 0;
        this.field_55 = 1;
    }

    @Inject(method = "<init>()V", at = @At("RETURN"))
    public void init(CallbackInfo ci) {
        this.field_82 = null;
        this.field_83 = 0;
        this.field_84 = false;
        this.field_85 = false;
        this.field_81 = false;
        this.field_86 = 0;
        this.field_87 = 0;
        this.field_88 = 0;
        this.field_89 = 0;
        this.field_90 = 0;
        this.field_91 = 0;
        this.field_92 = false;
        this.field_93 = 0.0f;
        this.field_94 = 0.0f;
        this.field_95 = 0.0f;
        this.field_96 = 0.0f;
        this.field_97 = 0.0f;
        this.field_98 = 0.0f;
        this.field_99 = 0.0f;
        this.field_100 = 0.0f;
        this.field_101 = 0.0f;
        this.field_102 = 0.0f;
        this.field_103 = 0.0f;
        this.field_104 = 0.0f;
        this.field_105 = 0.0f;
        this.field_41 = 0.0f;
        this.field_42 = 0.0f;
        this.field_43 = 0.0f;
        this.field_44 = 0.0f;
        this.field_45 = 0.0f;
        this.field_46 = 0.0f;
        this.field_47 = 0.0f;
        this.field_48 = 0.0f;
        this.field_49 = 0.0f;
        this.field_50 = 0.0f;
        this.field_51 = 0.0f;
        this.field_52 = 0.0f;
        this.field_53 = 0.0f;
        this.field_54 = 0.0f;
        this.field_55 = 0;
        this.field_56 = 0.0f;
        this.field_57 = 0.0f;
        this.field_58 = 0.0f;
        this.field_59 = 0.0f;
        this.field_60 = 0.0f;
        this.field_61 = 0.0f;
        this.field_62 = 0.0f;
        this.field_63 = 0.0f;
        this.field_64 = 0.0f;
        this.field_65 = 0.0f;
        this.field_66 = 0.0f;
        this.field_68 = 0.0f;
        this.field_69 = false;
        this.field_70 = false;
        this.field_71 = false;
        this.field_72 = false;
        this.field_73 = false;
        this.field_74 = false;
        this.field_75 = false;
        this.field_76 = false;
        this.field_77 = false;
        this.field_78 = false;
        this.field_79 = false;
        this.field_80 = false;
        this.field_83 = -1;
        this.field_84 = false;
        this.field_85 = false;
        this.field_81 = true;
        this.field_86 = 0;
        this.field_87 = 0;
        this.field_88 = 0;
        this.field_89 = 0;
        this.field_90 = 0;
        this.field_91 = 0;
        this.field_55 = 1;
    }

    @Environment(EnvType.CLIENT)
    @Redirect(method = "method_57", at = @At(value = "INVOKE", target = "Lnet/minecraft/block/BlockBase;method_1616(Lnet/minecraft/level/TileView;III)V"))
    public void renderBlockByRenderType(BlockBase block, TileView iBlockAccess, int i, int i1, int i2) {
        System.out.println("Eat shit");
        block.method_1616(this.field_82, i, i1, i2);
        ModLoader.renderWorldBlock((TileRenderer) (Object) this, field_82, i, i1, i2, block, block.method_1621());
    }
}
